import json
from datetime import datetime, timedelta
from pathlib import Path

# Default to roughly current time for mock generation
BASE_DIR = Path(__file__).resolve().parent
DATA_DIR = BASE_DIR / "data"
DATA_DIR.mkdir(parents=True, exist_ok=True)
NOW = datetime.fromisoformat("2026-07-30T10:00:00+07:00")

def date_str(days=0, hours=0):
    return (NOW + timedelta(days=days, hours=hours)).isoformat()

events = [
    {
        "id": "evt_mock_001",
        "is_mock": True,
        "title": "Workshop CV đầu tiên của bạn",
        "description": "Workshop hướng dẫn sinh viên chuẩn bị CV.",
        "topics": ["career", "skills"],
        "event_type": "workshop",
        "format": "offline",
        "cost": "free",
        "starts_at": date_str(days=2, hours=8),
        "ends_at": date_str(days=2, hours=10),
        "registration_deadline": date_str(days=1),
        "location": "Hội trường A",
        "organizer": "Phòng CTSV",
        "status": "published",
        "source_url": "https://example.invalid/events/evt_mock_001",
        "updated_at": date_str(days=-1),
        "conflicts": []
    },
    {
        "id": "evt_mock_002",
        "is_mock": True,
        "title": "Tech Talk: Từ ý tưởng đến MVP",
        "description": "Chia sẻ kinh nghiệm xây dựng MVP từ các startup công nghệ.",
        "topics": ["technology"],
        "event_type": "talkshow",
        "format": "offline",
        "cost": "free",
        "starts_at": date_str(days=3, hours=5), # this weekend
        "ends_at": date_str(days=3, hours=7),
        "registration_deadline": date_str(days=2),
        "location": "Lab 5.2",
        "organizer": "Khoa CNTT",
        "status": "published",
        "source_url": "https://example.invalid/events/evt_mock_002",
        "updated_at": date_str(days=-2),
        "conflicts": []
    },
    {
        "id": "evt_mock_003",
        "is_mock": True,
        "title": "Giao lưu sinh viên 5 tốt",
        "description": "Sự kiện miễn phí giao lưu sinh viên.",
        "topics": ["community"],
        "event_type": "networking",
        "format": "offline",
        "cost": "free",
        "starts_at": date_str(days=0, hours=9), # today
        "ends_at": date_str(days=0, hours=11),
        "registration_deadline": date_str(days=-1),
        "location": "Sân trường",
        "organizer": "Đoàn Thanh niên",
        "status": "published",
        "source_url": "https://example.invalid/events/evt_mock_003",
        "updated_at": date_str(days=-3),
        "conflicts": []
    },
    {
        "id": "evt_mock_004",
        "is_mock": True,
        "title": "Webinar: Tương lai của AI",
        "description": "Sự kiện online miễn phí về AI.",
        "topics": ["technology"],
        "event_type": "webinar",
        "format": "online",
        "cost": "free",
        "starts_at": date_str(days=8, hours=10), # next week
        "ends_at": date_str(days=8, hours=12),
        "registration_deadline": date_str(days=7),
        "location": "Google Meet",
        "organizer": "CLB AI",
        "status": "published",
        "source_url": "https://example.invalid/events/evt_mock_004",
        "updated_at": date_str(days=-1),
        "conflicts": []
    },
    {
        "id": "evt_mock_005",
        "is_mock": True,
        "title": "Workshop Kỹ năng thuyết trình",
        "description": "Kỹ năng thuyết trình chuyên nghiệp.",
        "topics": ["skills"],
        "event_type": "workshop",
        "format": "offline",
        "cost": "paid",
        "starts_at": date_str(days=15, hours=8), # this month
        "ends_at": date_str(days=15, hours=11),
        "registration_deadline": date_str(days=10),
        "location": "Phòng 301",
        "organizer": "Trung tâm kỹ năng mềm",
        "status": "published",
        "source_url": "https://example.invalid/events/evt_mock_005",
        "updated_at": date_str(days=-5),
        "conflicts": []
    },
    {
        "id": "evt_mock_006",
        "is_mock": True,
        "title": "Cuộc thi lập trình Hackathon K4",
        "description": "Cuộc thi lập trình lớn nhất trường.",
        "topics": ["technology", "learning"],
        "event_type": "competition",
        "format": "offline",
        "cost": "free",
        "starts_at": date_str(days=20, hours=0),
        "ends_at": date_str(days=22, hours=0),
        "registration_deadline": date_str(days=10),
        "location": "Nhà thi đấu",
        "organizer": "Khoa CNTT",
        "status": "published",
        "source_url": "https://example.invalid/events/evt_mock_006",
        "updated_at": date_str(days=-5),
        "conflicts": []
    },
    {
        "id": "evt_mock_007",
        "is_mock": True,
        "title": "Seminar Blockchain: Cơ hội và Thách thức",
        "description": "Tìm hiểu về blockchain tại Đà Nẵng.",
        "topics": ["technology"],
        "event_type": "seminar",
        "format": "offline",
        "cost": "free",
        "starts_at": date_str(days=30, hours=8),
        "ends_at": date_str(days=30, hours=11),
        "registration_deadline": date_str(days=25),
        "location": "Khách sạn X, Đà Nẵng",
        "organizer": "Tech Danang",
        "status": "published",
        "source_url": "https://example.invalid/events/evt_mock_007",
        "updated_at": date_str(days=-10),
        "conflicts": []
    },
    {
        "id": "evt_mock_008",
        "is_mock": True,
        "title": "Talkshow Hành trang du học",
        "description": "Chuẩn bị gì để đi du học?",
        "topics": ["learning"],
        "event_type": "talkshow",
        "format": "offline",
        "cost": "free",
        "starts_at": date_str(days=4, hours=6),
        "ends_at": date_str(days=4, hours=8),
        "registration_deadline": date_str(days=3),
        "location": "Hội trường B",
        "organizer": "Phòng Hợp tác Quốc tế",
        "status": "published",
        "source_url": "https://example.invalid/events/evt_mock_008",
        "updated_at": date_str(days=-2),
        "conflicts": []
    },
    # needs_confirmation conflict
    {
        "id": "evt_mock_009",
        "is_mock": True,
        "title": "Workshop Data Science",
        "description": "Workshop thực hành Data Science.",
        "topics": ["technology", "learning"],
        "event_type": "workshop",
        "format": "offline",
        "cost": "free",
        "starts_at": date_str(days=5, hours=7),
        "ends_at": date_str(days=5, hours=9),
        "registration_deadline": date_str(days=4),
        "location": "Lab 2.1",
        "organizer": "CLB Data",
        "status": "needs_confirmation",
        "source_url": "https://example.invalid/events/evt_mock_009",
        "updated_at": date_str(days=-1),
        "conflicts": [
            {
                "field": "starts_at",
                "values": [date_str(days=5, hours=7), date_str(days=5, hours=8)]
            }
        ]
    },
    # cancelled
    {
        "id": "evt_mock_010",
        "is_mock": True,
        "title": "Ngày hội việc làm Job Fair 2026",
        "description": "Ngày hội việc làm",
        "topics": ["career", "community"],
        "event_type": "fair",
        "format": "offline",
        "cost": "free",
        "starts_at": date_str(days=10, hours=1),
        "ends_at": date_str(days=10, hours=9),
        "registration_deadline": date_str(days=5),
        "location": "Sân vận động",
        "organizer": "Phòng CTSV",
        "status": "cancelled",
        "source_url": "https://example.invalid/events/evt_mock_010",
        "updated_at": date_str(days=-1),
        "conflicts": []
    },
    # past deadline
    {
        "id": "evt_mock_011",
        "is_mock": True,
        "title": "Khóa học Kỹ năng lãnh đạo",
        "description": "Dành cho cán bộ Đoàn Hội",
        "topics": ["skills", "learning"],
        "event_type": "course",
        "format": "offline",
        "cost": "paid",
        "starts_at": date_str(days=5, hours=8),
        "ends_at": date_str(days=5, hours=11),
        "registration_deadline": date_str(days=-2), # past deadline
        "location": "Phòng họp 1",
        "organizer": "Đoàn Thanh niên",
        "status": "published",
        "source_url": "https://example.invalid/events/evt_mock_011",
        "updated_at": date_str(days=-3),
        "conflicts": []
    },
    {
        "id": "evt_mock_012",
        "is_mock": True,
        "title": "Workshop Lập trình AI Agent với LangChain & LangGraph",
        "description": "Hướng dẫn xây dựng AI Agent đa tác vụ ứng dụng thực tế.",
        "topics": ["technology", "learning"],
        "event_type": "workshop",
        "format": "online",
        "cost": "free",
        "starts_at": date_str(days=1, hours=9), # tomorrow
        "ends_at": date_str(days=1, hours=11),
        "registration_deadline": date_str(days=1, hours=2),
        "location": "Zoom Meeting",
        "organizer": "CLB AI & Big Data",
        "status": "published",
        "source_url": "https://example.invalid/events/evt_mock_012",
        "updated_at": date_str(days=-1),
        "conflicts": []
    },
    {
        "id": "evt_mock_013",
        "is_mock": True,
        "title": "Hội thảo Bảo mật thông tin & An ninh mạng 2026",
        "description": "Cập nhật các xu hướng tấn công mạng và phương pháp bảo mật mới.",
        "topics": ["technology"],
        "event_type": "seminar",
        "format": "offline",
        "cost": "free",
        "starts_at": date_str(days=4, hours=3), # this weekend
        "ends_at": date_str(days=4, hours=6),
        "registration_deadline": date_str(days=3),
        "location": "Hội trường C",
        "organizer": "Khoa An toàn Thông tin",
        "status": "published",
        "source_url": "https://example.invalid/events/evt_mock_013",
        "updated_at": date_str(days=-2),
        "conflicts": []
    },
    {
        "id": "evt_mock_014",
        "is_mock": True,
        "title": "Workshop Thiết kế UI/UX cho người mới bắt đầu",
        "description": "Thực hành thiết kế giao diện ứng dụng di động với Figma.",
        "topics": ["skills", "technology"],
        "event_type": "workshop",
        "format": "offline",
        "cost": "paid",
        "starts_at": date_str(days=6, hours=8),
        "ends_at": date_str(days=6, hours=11),
        "registration_deadline": date_str(days=4),
        "location": "Phòng Lab 3.1",
        "organizer": "CLB Thiết kế Đồ họa",
        "status": "published",
        "source_url": "https://example.invalid/events/evt_mock_014",
        "updated_at": date_str(days=-1),
        "conflicts": []
    },
    {
        "id": "evt_mock_015",
        "is_mock": True,
        "title": "Talkshow: Bí quyết săn học bổng du học Mỹ & Châu Âu",
        "description": "Chia sẻ kinh nghiệm làm hồ sơ, bài luận và phỏng vấn học bổng.",
        "topics": ["learning", "career"],
        "event_type": "talkshow",
        "format": "online",
        "cost": "free",
        "starts_at": date_str(days=7, hours=10),
        "ends_at": date_str(days=7, hours=12),
        "registration_deadline": date_str(days=5),
        "location": "MS Teams",
        "organizer": "Trung tâm Du học & Hợp tác Quốc tế",
        "status": "published",
        "source_url": "https://example.invalid/events/evt_mock_015",
        "updated_at": date_str(days=-3),
        "conflicts": []
    },
    {
        "id": "evt_mock_016",
        "is_mock": True,
        "title": "Cuộc thi Mobile App Challenge 2026",
        "description": "Sân chơi phát triển ứng dụng iOS / Android cho sinh viên toàn trường.",
        "topics": ["technology", "learning"],
        "event_type": "competition",
        "format": "offline",
        "cost": "free",
        "starts_at": date_str(days=12, hours=0),
        "ends_at": date_str(days=14, hours=0),
        "registration_deadline": date_str(days=8),
        "location": "Khu Công nghệ cao",
        "organizer": "Khoa CNTT & Doanh nghiệp Tài trợ",
        "status": "published",
        "source_url": "https://example.invalid/events/evt_mock_016",
        "updated_at": date_str(days=-4),
        "conflicts": []
    },
    {
        "id": "evt_mock_017",
        "is_mock": True,
        "title": "CLB Tiếng Anh: English Communication Club Meeting",
        "description": "Sinh hoạt chủ đề 'Future of Tech Work' để nâng cao phản xạ tiếng Anh.",
        "topics": ["skills", "community"],
        "event_type": "networking",
        "format": "offline",
        "cost": "free",
        "starts_at": date_str(days=2, hours=11), # this weekend
        "ends_at": date_str(days=2, hours=13),
        "registration_deadline": date_str(days=1),
        "location": "Căn tin Trung tâm",
        "organizer": "CLB Tiếng Anh Sinh viên",
        "status": "published",
        "source_url": "https://example.invalid/events/evt_mock_017",
        "updated_at": date_str(days=-1),
        "conflicts": []
    },
    {
        "id": "evt_mock_018",
        "is_mock": True,
        "title": "Webinar: Giới thiệu Điện toán đám mây & AWS Cloud",
        "description": "Tổng quan kiến trúc Cloud Computing và cách nhận voucher AWS Educate.",
        "topics": ["technology"],
        "event_type": "webinar",
        "format": "online",
        "cost": "free",
        "starts_at": date_str(days=9, hours=9),
        "ends_at": date_str(days=9, hours=11),
        "registration_deadline": date_str(days=7),
        "location": "YouTube LiveStream",
        "organizer": "AWS Student Community",
        "status": "published",
        "source_url": "https://example.invalid/events/evt_mock_018",
        "updated_at": date_str(days=-2),
        "conflicts": []
    },
    {
        "id": "evt_mock_019",
        "is_mock": True,
        "title": "Khóa học Python căn bản cho Data Analysis",
        "description": "Khóa học 4 buổi thực hành Pandas, NumPy và Matplotlib.",
        "topics": ["technology", "learning"],
        "event_type": "course",
        "format": "online",
        "cost": "paid",
        "starts_at": date_str(days=11, hours=8),
        "ends_at": date_str(days=11, hours=11),
        "registration_deadline": date_str(days=9),
        "location": "Google Meet",
        "organizer": "Viện Công nghệ Dữ liệu",
        "status": "published",
        "source_url": "https://example.invalid/events/evt_mock_019",
        "updated_at": date_str(days=-3),
        "conflicts": []
    },
    {
        "id": "evt_mock_020",
        "is_mock": True,
        "title": "Ngày hội Kết nối Doanh nghiệp & Tuyển dụng IT",
        "description": "Cơ hội phỏng vấn trực tiếp vị trí Thực tập sinh / Junior từ hơn 30 công ty IT.",
        "topics": ["career", "community"],
        "event_type": "fair",
        "format": "offline",
        "cost": "free",
        "starts_at": date_str(days=18, hours=1),
        "ends_at": date_str(days=18, hours=8),
        "registration_deadline": date_str(days=14),
        "location": "Sảnh A1",
        "organizer": "Trung tâm Quan hệ Doanh nghiệp",
        "status": "published",
        "source_url": "https://example.invalid/events/evt_mock_020",
        "updated_at": date_str(days=-5),
        "conflicts": []
    },
    {
        "id": "evt_mock_021",
        "is_mock": True,
        "title": "Workshop Quản lý thời gian & Nâng cao hiệu suất",
        "description": "Phương pháp Pomodoro, Eisenhower Matrix để làm chủ lịch trình học tập.",
        "topics": ["skills"],
        "event_type": "workshop",
        "format": "online",
        "cost": "free",
        "starts_at": date_str(days=3, hours=11), # this weekend
        "ends_at": date_str(days=3, hours=12),
        "registration_deadline": date_str(days=2),
        "location": "Zoom Meeting",
        "organizer": "CLB Phấn Đấu",
        "status": "published",
        "source_url": "https://example.invalid/events/evt_mock_021",
        "updated_at": date_str(days=-1),
        "conflicts": []
    },
    {
        "id": "evt_mock_022",
        "is_mock": True,
        "title": "Seminar Công nghệ Game 3D với Unity & Unreal Engine",
        "description": "Trải nghiệm quy trình làm game 3D từ đồ họa đến lập trình physics.",
        "topics": ["technology"],
        "event_type": "seminar",
        "format": "offline",
        "cost": "free",
        "starts_at": date_str(days=16, hours=7),
        "ends_at": date_str(days=16, hours=10),
        "registration_deadline": date_str(days=12),
        "location": "Phòng Chuyên đề 2",
        "organizer": "CLB Game Development",
        "status": "published",
        "source_url": "https://example.invalid/events/evt_mock_022",
        "updated_at": date_str(days=-4),
        "conflicts": []
    },
    {
        "id": "evt_mock_023",
        "is_mock": True,
        "title": "Cuộc thi Ý tưởng Startup Học sinh Sinh viên",
        "description": "Vòng sơ loại trình bày dự án đổi mới sáng tạo trước các nhà đầu tư.",
        "topics": ["career", "community"],
        "event_type": "competition",
        "format": "offline",
        "cost": "free",
        "starts_at": date_str(days=25, hours=1),
        "ends_at": date_str(days=25, hours=9),
        "registration_deadline": date_str(days=20),
        "location": "Hội trường Trung tâm",
        "organizer": "Vườn ươm Khởi nghiệp",
        "status": "published",
        "source_url": "https://example.invalid/events/evt_mock_023",
        "updated_at": date_str(days=-6),
        "conflicts": []
    },
    {
        "id": "evt_mock_024",
        "is_mock": True,
        "title": "Workshop Prompt Engineering & AI Tools cho sinh viên",
        "description": "Ứng dụng ChatGPT, Claude, Midjourney để tối ưu công việc nghiên cứu và học tập.",
        "topics": ["technology", "skills"],
        "event_type": "workshop",
        "format": "offline",
        "cost": "free",
        "starts_at": date_str(days=5, hours=11),
        "ends_at": date_str(days=5, hours=13),
        "registration_deadline": date_str(days=4),
        "location": "Lab 4.2",
        "organizer": "Khoa CNTT",
        "status": "published",
        "source_url": "https://example.invalid/events/evt_mock_024",
        "updated_at": date_str(days=-1),
        "conflicts": []
    },
    {
        "id": "evt_mock_025",
        "is_mock": True,
        "title": "Networking Night: Đêm kết nối Cộng đồng Cựu sinh viên",
        "description": "Giao lưu, ăn tối và chia sẻ cơ hội việc làm cùng các cựu sinh viên thành công.",
        "topics": ["community", "career"],
        "event_type": "networking",
        "format": "offline",
        "cost": "paid",
        "starts_at": date_str(days=13, hours=11),
        "ends_at": date_str(days=13, hours=14),
        "registration_deadline": date_str(days=10),
        "location": "Sky Bar & Lounge",
        "organizer": "Ban LL Cựu Sinh viên",
        "status": "published",
        "source_url": "https://example.invalid/events/evt_mock_025",
        "updated_at": date_str(days=-2),
        "conflicts": []
    }
]

with (DATA_DIR / 'events.json').open('w', encoding='utf-8') as f:
    json.dump({"items": events, "total": len(events), "data_version": "cp3-seed-v1"}, f, ensure_ascii=False, indent=2)

print("Created backend/data/events.json")

# Golden set is curated manually in eval/golden-set.jsonl.
# Do not regenerate it from mock-data code: eval cases are immutable test evidence.
with (DATA_DIR / 'README.md').open('w', encoding='utf-8') as f:
    f.write("# Mock Event Data\n\nDữ liệu tự sinh cho hackathon, không đại diện cho sự kiện thật. Các sự kiện bao gồm mâu thuẫn giờ, hết hạn, và hủy bỏ để test AI.\n")

with (DATA_DIR / 'data-version.txt').open('w', encoding='utf-8') as f:
    f.write("cp3-seed-v1\n")

