import json
from datetime import datetime, timedelta
from pathlib import Path

# Default to roughly current time for mock generation
BASE_DIR = Path(__file__).resolve().parent
DATA_DIR = BASE_DIR / "data"
DATA_DIR.mkdir(parents=True, exist_ok=True)
NOW = datetime.fromisoformat("2026-07-30T10:00:00+07:00")

def date_str(days=0, hours=0):
    return (NOW + timedelta(days=days, hours=hours)).isoformat()

events = [
    {
        "id": "evt_mock_001",
        "is_mock": True,
        "title": "Workshop CV đầu tiên của bạn",
        "description": "Workshop hướng dẫn sinh viên chuẩn bị CV.",
        "topics": ["career", "skills"],
        "event_type": "workshop",
        "format": "offline",
        "cost": "free",
        "starts_at": date_str(days=2, hours=8),
        "ends_at": date_str(days=2, hours=10),
        "registration_deadline": date_str(days=1),
        "location": "Hội trường A",
        "organizer": "Phòng CTSV",
        "status": "published",
        "source_url": "https://example.invalid/events/evt_mock_001",
        "updated_at": date_str(days=-1),
        "conflicts": []
    },
    {
        "id": "evt_mock_002",
        "is_mock": True,
        "title": "Tech Talk: Từ ý tưởng đến MVP",
        "description": "Chia sẻ kinh nghiệm xây dựng MVP từ các startup công nghệ.",
        "topics": ["technology"],
        "event_type": "talkshow",
        "format": "offline",
        "cost": "free",
        "starts_at": date_str(days=3, hours=5), # this weekend
        "ends_at": date_str(days=3, hours=7),
        "registration_deadline": date_str(days=2),
        "location": "Lab 5.2",
        "organizer": "Khoa CNTT",
        "status": "published",
        "source_url": "https://example.invalid/events/evt_mock_002",
        "updated_at": date_str(days=-2),
        "conflicts": []
    },
    {
        "id": "evt_mock_003",
        "is_mock": True,
        "title": "Giao lưu sinh viên 5 tốt",
        "description": "Sự kiện miễn phí giao lưu sinh viên.",
        "topics": ["community"],
        "event_type": "networking",
        "format": "offline",
        "cost": "free",
        "starts_at": date_str(days=0, hours=9), # today
        "ends_at": date_str(days=0, hours=11),
        "registration_deadline": date_str(days=-1),
        "location": "Sân trường",
        "organizer": "Đoàn Thanh niên",
        "status": "published",
        "source_url": "https://example.invalid/events/evt_mock_003",
        "updated_at": date_str(days=-3),
        "conflicts": []
    },
    {
        "id": "evt_mock_004",
        "is_mock": True,
        "title": "Webinar: Tương lai của AI",
        "description": "Sự kiện online miễn phí về AI.",
        "topics": ["technology"],
        "event_type": "webinar",
        "format": "online",
        "cost": "free",
        "starts_at": date_str(days=8, hours=10), # next week
        "ends_at": date_str(days=8, hours=12),
        "registration_deadline": date_str(days=7),
        "location": "Google Meet",
        "organizer": "CLB AI",
        "status": "published",
        "source_url": "https://example.invalid/events/evt_mock_004",
        "updated_at": date_str(days=-1),
        "conflicts": []
    },
    {
        "id": "evt_mock_005",
        "is_mock": True,
        "title": "Workshop Kỹ năng thuyết trình",
        "description": "Kỹ năng thuyết trình chuyên nghiệp.",
        "topics": ["skills"],
        "event_type": "workshop",
        "format": "offline",
        "cost": "paid",
        "starts_at": date_str(days=15, hours=8), # this month
        "ends_at": date_str(days=15, hours=11),
        "registration_deadline": date_str(days=10),
        "location": "Phòng 301",
        "organizer": "Trung tâm kỹ năng mềm",
        "status": "published",
        "source_url": "https://example.invalid/events/evt_mock_005",
        "updated_at": date_str(days=-5),
        "conflicts": []
    },
    {
        "id": "evt_mock_006",
        "is_mock": True,
        "title": "Cuộc thi lập trình Hackathon K4",
        "description": "Cuộc thi lập trình lớn nhất trường.",
        "topics": ["technology", "learning"],
        "event_type": "competition",
        "format": "offline",
        "cost": "free",
        "starts_at": date_str(days=20, hours=0),
        "ends_at": date_str(days=22, hours=0),
        "registration_deadline": date_str(days=10),
        "location": "Nhà thi đấu",
        "organizer": "Khoa CNTT",
        "status": "published",
        "source_url": "https://example.invalid/events/evt_mock_006",
        "updated_at": date_str(days=-5),
        "conflicts": []
    },
    {
        "id": "evt_mock_007",
        "is_mock": True,
        "title": "Seminar Blockchain: Cơ hội và Thách thức",
        "description": "Tìm hiểu về blockchain tại Đà Nẵng.",
        "topics": ["technology"],
        "event_type": "seminar",
        "format": "offline",
        "cost": "free",
        "starts_at": date_str(days=30, hours=8),
        "ends_at": date_str(days=30, hours=11),
        "registration_deadline": date_str(days=25),
        "location": "Khách sạn X, Đà Nẵng",
        "organizer": "Tech Danang",
        "status": "published",
        "source_url": "https://example.invalid/events/evt_mock_007",
        "updated_at": date_str(days=-10),
        "conflicts": []
    },
    {
        "id": "evt_mock_008",
        "is_mock": True,
        "title": "Talkshow Hành trang du học",
        "description": "Chuẩn bị gì để đi du học?",
        "topics": ["learning"],
        "event_type": "talkshow",
        "format": "offline",
        "cost": "free",
        "starts_at": date_str(days=4, hours=6),
        "ends_at": date_str(days=4, hours=8),
        "registration_deadline": date_str(days=3),
        "location": "Hội trường B",
        "organizer": "Phòng Hợp tác Quốc tế",
        "status": "published",
        "source_url": "https://example.invalid/events/evt_mock_008",
        "updated_at": date_str(days=-2),
        "conflicts": []
    },
    # needs_confirmation conflict
    {
        "id": "evt_mock_009",
        "is_mock": True,
        "title": "Workshop Data Science",
        "description": "Workshop thực hành Data Science.",
        "topics": ["technology", "learning"],
        "event_type": "workshop",
        "format": "offline",
        "cost": "free",
        "starts_at": date_str(days=5, hours=7),
        "ends_at": date_str(days=5, hours=9),
        "registration_deadline": date_str(days=4),
        "location": "Lab 2.1",
        "organizer": "CLB Data",
        "status": "needs_confirmation",
        "source_url": "https://example.invalid/events/evt_mock_009",
        "updated_at": date_str(days=-1),
        "conflicts": [
            {
                "field": "starts_at",
                "values": [date_str(days=5, hours=7), date_str(days=5, hours=8)]
            }
        ]
    },
    # cancelled
    {
        "id": "evt_mock_010",
        "is_mock": True,
        "title": "Ngày hội việc làm Job Fair 2026",
        "description": "Ngày hội việc làm",
        "topics": ["career", "community"],
        "event_type": "fair",
        "format": "offline",
        "cost": "free",
        "starts_at": date_str(days=10, hours=1),
        "ends_at": date_str(days=10, hours=9),
        "registration_deadline": date_str(days=5),
        "location": "Sân vận động",
        "organizer": "Phòng CTSV",
        "status": "cancelled",
        "source_url": "https://example.invalid/events/evt_mock_010",
        "updated_at": date_str(days=-1),
        "conflicts": []
    },
    # past deadline
    {
        "id": "evt_mock_011",
        "is_mock": True,
        "title": "Khóa học Kỹ năng lãnh đạo",
        "description": "Dành cho cán bộ Đoàn Hội",
        "topics": ["skills", "learning"],
        "event_type": "course",
        "format": "offline",
        "cost": "paid",
        "starts_at": date_str(days=5, hours=8),
        "ends_at": date_str(days=5, hours=11),
        "registration_deadline": date_str(days=-2), # past deadline
        "location": "Phòng họp 1",
        "organizer": "Đoàn Thanh niên",
        "status": "published",
        "source_url": "https://example.invalid/events/evt_mock_011",
        "updated_at": date_str(days=-3),
        "conflicts": []
    },
    {
        "id": "evt_mock_012",
        "is_mock": True,
        "title": "Webinar: Nhập môn DevOps & CI/CD",
        "description": "Hướng dẫn cài đặt và sử dụng Docker, GitHub Actions cho dự án thực tế.",
        "topics": ["technology"],
        "event_type": "webinar",
        "format": "online",
        "cost": "free",
        "starts_at": date_str(days=12, hours=9),
        "ends_at": date_str(days=12, hours=11),
        "registration_deadline": date_str(days=11),
        "location": "Microsoft Teams",
        "organizer": "CLB DevOps",
        "status": "published",
        "source_url": "https://example.invalid/events/evt_mock_012",
        "updated_at": date_str(days=-2),
        "conflicts": []
    },
    {
        "id": "evt_mock_013",
        "is_mock": True,
        "title": "Workshop An toàn thông tin và An ninh mạng",
        "description": "Tìm hiểu về các phương thức tấn công phổ biến và kỹ năng phòng ngừa.",
        "topics": ["technology"],
        "event_type": "workshop",
        "format": "offline",
        "cost": "free",
        "starts_at": date_str(days=16, hours=8),
        "ends_at": date_str(days=16, hours=10),
        "registration_deadline": date_str(days=14),
        "location": "Phòng Lab 3",
        "organizer": "Khoa CNTT",
        "status": "needs_confirmation",
        "source_url": "https://example.invalid/events/evt_mock_013",
        "updated_at": date_str(days=-1),
        "conflicts": [
            {
                "field": "location",
                "values": ["Phòng Lab 3", "Phòng Lab 4"]
            }
        ]
    },
    {
        "id": "evt_mock_014",
        "is_mock": True,
        "title": "Talkshow Phỏng vấn Tiếng Anh cùng Nhà tuyển dụng",
        "description": "Bí quyết trả lời câu hỏi phỏng vấn bằng Tiếng Anh tự tin.",
        "topics": ["career", "skills"],
        "event_type": "talkshow",
        "format": "offline",
        "cost": "free",
        "starts_at": date_str(days=7, hours=4),
        "ends_at": date_str(days=7, hours=6),
        "registration_deadline": date_str(days=-1),
        "location": "Hội trường C",
        "organizer": "Phòng CTSV",
        "status": "published",
        "source_url": "https://example.invalid/events/evt_mock_014",
        "updated_at": date_str(days=-3),
        "conflicts": []
    },
    {
        "id": "evt_mock_015",
        "is_mock": True,
        "title": "Khóa học Quản lý thời gian và Năng suất cá nhân",
        "description": "Phương pháp Eisenhower và Pomodoro áp dụng cho sinh viên.",
        "topics": ["skills"],
        "event_type": "course",
        "format": "offline",
        "cost": "paid",
        "starts_at": date_str(days=11, hours=8),
        "ends_at": date_str(days=11, hours=10),
        "registration_deadline": date_str(days=9),
        "location": "Phòng 402",
        "organizer": "Trung tâm kỹ năng mềm",
        "status": "published",
        "source_url": "https://example.invalid/events/evt_mock_015",
        "updated_at": date_str(days=-2),
        "conflicts": []
    },
    {
        "id": "evt_mock_016",
        "is_mock": True,
        "title": "Chiến dịch Tình nguyện Mùa hè xanh 2026",
        "description": "Hoạt động tình nguyện hỗ trợ bà con vùng xa.",
        "topics": ["community"],
        "event_type": "networking",
        "format": "offline",
        "cost": "free",
        "starts_at": date_str(days=18, hours=0),
        "ends_at": date_str(days=25, hours=0),
        "registration_deadline": date_str(days=12),
        "location": "Huyện Hòa Vang, Đà Nẵng",
        "organizer": "Đoàn Thanh niên",
        "status": "published",
        "source_url": "https://example.invalid/events/evt_mock_016",
        "updated_at": date_str(days=-4),
        "conflicts": []
    },
    {
        "id": "evt_mock_017",
        "is_mock": True,
        "title": "Workshop Điện toán đám mây với AWS",
        "description": "Khởi tạo máy chủ EC2 và cấu hình S3 cho ứng dụng web.",
        "topics": ["technology"],
        "event_type": "workshop",
        "format": "online",
        "cost": "paid",
        "starts_at": date_str(days=22, hours=9),
        "ends_at": date_str(days=22, hours=11),
        "registration_deadline": date_str(days=20),
        "location": "Zoom Online",
        "organizer": "CLB Cloud Computing",
        "status": "needs_confirmation",
        "source_url": "https://example.invalid/events/evt_mock_017",
        "updated_at": date_str(days=-1),
        "conflicts": [
            {
                "field": "starts_at",
                "values": [date_str(days=22, hours=9), date_str(days=22, hours=10)]
            }
        ]
    },
    {
        "id": "evt_mock_018",
        "is_mock": True,
        "title": "Workshop Thiết kế Portfolio ấn tượng cho Designer",
        "description": "Hướng dẫn xây dựng UI/UX Portfolio thu hút nhà tuyển dụng.",
        "topics": ["career"],
        "event_type": "workshop",
        "format": "offline",
        "cost": "paid",
        "starts_at": date_str(days=9, hours=4),
        "ends_at": date_str(days=9, hours=7),
        "registration_deadline": date_str(days=-3),
        "location": "Phòng Studio 1",
        "organizer": "CLB Thiết Kế",
        "status": "published",
        "source_url": "https://example.invalid/events/evt_mock_018",
        "updated_at": date_str(days=-5),
        "conflicts": []
    },
    {
        "id": "evt_mock_019",
        "is_mock": True,
        "title": "Đêm nhạc Giao lưu CLB Âm nhạc",
        "description": "Chương trình ca nhạc sinh viên giao lưu các câu lạc bộ nghệ thuật.",
        "topics": ["community"],
        "event_type": "networking",
        "format": "offline",
        "cost": "free",
        "starts_at": date_str(days=6, hours=9),
        "ends_at": date_str(days=6, hours=11),
        "registration_deadline": date_str(days=5),
        "location": "Sân khấu ngoài trời",
        "organizer": "CLB Âm nhạc",
        "status": "published",
        "source_url": "https://example.invalid/events/evt_mock_019",
        "updated_at": date_str(days=-1),
        "conflicts": []
    },
    {
        "id": "evt_mock_020",
        "is_mock": True,
        "title": "Webinar Phương pháp học tập thông minh thời 4.0",
        "description": "Ứng dụng sơ đồ tư duy và công cụ AI hỗ trợ việc học đại học.",
        "topics": ["learning"],
        "event_type": "webinar",
        "format": "online",
        "cost": "free",
        "starts_at": date_str(days=14, hours=9),
        "ends_at": date_str(days=14, hours=11),
        "registration_deadline": date_str(days=13),
        "location": "Google Meet",
        "organizer": "Hội Sinh viên",
        "status": "published",
        "source_url": "https://example.invalid/events/evt_mock_020",
        "updated_at": date_str(days=-2),
        "conflicts": []
    },
    {
        "id": "evt_mock_021",
        "is_mock": True,
        "title": "Lập trình ứng dụng Mobile với Flutter",
        "description": "Xây dựng ứng dụng đa nền tảng iOS và Android từ A-Z.",
        "topics": ["technology"],
        "event_type": "seminar",
        "format": "offline",
        "cost": "free",
        "starts_at": date_str(days=17, hours=4),
        "ends_at": date_str(days=17, hours=7),
        "registration_deadline": date_str(days=15),
        "location": "Hội trường C",
        "organizer": "CLB Mobile Dev",
        "status": "published",
        "source_url": "https://example.invalid/events/evt_mock_021",
        "updated_at": date_str(days=-2),
        "conflicts": []
    },
    {
        "id": "evt_mock_022",
        "is_mock": True,
        "title": "Khóa học Kỹ năng Viết Email và Báo cáo Chuyên nghiệp",
        "description": "Rèn luyện văn phong làm việc trong môi trường doanh nghiệp.",
        "topics": ["skills", "career"],
        "event_type": "course",
        "format": "offline",
        "cost": "paid",
        "starts_at": date_str(days=26, hours=8),
        "ends_at": date_str(days=26, hours=10),
        "registration_deadline": date_str(days=24),
        "location": "Phòng 204",
        "organizer": "Trung tâm kỹ năng mềm",
        "status": "published",
        "source_url": "https://example.invalid/events/evt_mock_022",
        "updated_at": date_str(days=-4),
        "conflicts": []
    },
    {
        "id": "evt_mock_023",
        "is_mock": True,
        "title": "Ngày hội Sách cũ và Trao đổi Tri thức",
        "description": "Sự kiện quyên góp và trao đổi giáo trình, sách tham khảo.",
        "topics": ["community", "learning"],
        "event_type": "fair",
        "format": "offline",
        "cost": "free",
        "starts_at": date_str(days=13, hours=1),
        "ends_at": date_str(days=13, hours=7),
        "registration_deadline": date_str(days=10),
        "location": "Sảnh nhà A",
        "organizer": "CLB Sách & Thư viện",
        "status": "cancelled",
        "source_url": "https://example.invalid/events/evt_mock_023",
        "updated_at": date_str(days=-1),
        "conflicts": []
    },
    {
        "id": "evt_mock_024",
        "is_mock": True,
        "title": "Khóa học Tiếng Anh giao tiếp công sở",
        "description": "Tăng phản xạ giao tiếp với giảng viên bản xứ.",
        "topics": ["skills", "learning"],
        "event_type": "course",
        "format": "offline",
        "cost": "paid",
        "starts_at": date_str(days=28, hours=8),
        "ends_at": date_str(days=28, hours=10),
        "registration_deadline": date_str(days=26),
        "location": "Phòng Ngoại ngữ 2",
        "organizer": "Trung tâm Ngoại ngữ",
        "status": "published",
        "source_url": "https://example.invalid/events/evt_mock_024",
        "updated_at": date_str(days=-3),
        "conflicts": []
    },
    {
        "id": "evt_mock_025",
        "is_mock": True,
        "title": "Workshop Xử lý dữ liệu cơ bản với Python",
        "description": "Thực hành Pandas, Numpy cho người mới bắt đầu.",
        "topics": ["technology", "learning"],
        "event_type": "workshop",
        "format": "online",
        "cost": "free",
        "starts_at": date_str(days=24, hours=9),
        "ends_at": date_str(days=24, hours=11),
        "registration_deadline": date_str(days=22),
        "location": "Google Meet",
        "organizer": "CLB Python",
        "status": "published",
        "source_url": "https://example.invalid/events/evt_mock_025",
        "updated_at": date_str(days=-1),
        "conflicts": []
    }
]

with (DATA_DIR / 'events.json').open('w', encoding='utf-8') as f:
    json.dump({"items": events, "total": len(events), "data_version": "cp3-seed-v1"}, f, ensure_ascii=False, indent=2)

print("Created backend/data/events.json")

# Golden set is curated manually in eval/golden-set.jsonl.
# Do not regenerate it from mock-data code: eval cases are immutable test evidence.
with (DATA_DIR / 'README.md').open('w', encoding='utf-8') as f:
    f.write("# Mock Event Data\n\nDữ liệu tự sinh cho hackathon, không đại diện cho sự kiện thật. Các sự kiện bao gồm mâu thuẫn giờ, hết hạn, và hủy bỏ để test AI.\n")

with (DATA_DIR / 'data-version.txt').open('w', encoding='utf-8') as f:
    f.write("cp3-seed-v1\n")

